---
- name: Install php 7.0 fpm
  apt:
    pkg: php7.0-fpm
    state: present
    install_recommends: no

- name: Creating /run/php directory
  file: 
    path: /run/php
    state: directory
    owner: www-data
    mode: u=rwx,g=rx,o=rx

- name: "Creating /var/log/php directory owner by www-data"
  file: 
    path: /var/log/php
    state: directory
    owner: www-data
    mode: u=rwx,g=rx,o=rx

- name: Adding "/etc/php/7.0/fpm/php.ini" to "php_ini_path_list" array
  set_fact: 
    php_ini_path_list: "{{ php_ini_path_list + [ '/etc/php/7.0/fpm/php.ini' ] }} "

- name: Set max_execution_time to 90 for fpm php.ini
  ini_file:
    dest: /etc/php/7.0/fpm/php.ini
    section: PHP
    option: max_execution_time
    value: Off

- name: "Change owner to www-data for /etc/php"
  file:
    dest: /etc/php
    owner: www-data
    recurse: yes

- name: Set error_log to "/var/log/php/error.log" in php-fpm.conf
  ini_file:
    dest: /etc/php/7.0/fpm/php-fpm.conf
    section: global
    option: error_log
    value: /var/log/php/error.log

- name: Set log_level to "notice" in php-fpm.conf
  ini_file:
    dest: /etc/php/7.0/fpm/php-fpm.conf
    section: global
    option: log_level 
    value: notice
    
- name: Set daemonize to no in php-fpm.conf
  ini_file:
    dest: /etc/php/7.0/fpm/php-fpm.conf
    section: global
    option: daemonize
    value: "no"
    
- name: Remove user directive from www.conf
  lineinfile:
    dest: '/etc/php/7.0/fpm/pool.d/www.conf'
    regexp: '^\s*\;{0,1}\s*user'
    state: absent

- name: Remove group directive from www.conf
  lineinfile:
    dest: '/etc/php/7.0/fpm/pool.d/www.conf'
    regexp: '^\s*\;{0,1}\s*group'
    state: absent

- name: Set listen to 9000 in www.conf
  ini_file:
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    section: www
    option: listen 
    value: 9000

- name: Set request_terminate_timeout to "180s" in www.conf
  ini_file:
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    section: www
    option: request_terminate_timeout 
    value: 180s

- name: Set request_slowlog_timeout to "180s" in www.conf
  ini_file:
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    section: www
    option: request_slowlog_timeout 
    value: 10s

- name: Set slowlog to "/var/log/php/slow.log" in www.conf
  ini_file:
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    section: www
    option: slowlog
    value: /var/log/php/slow.log

- name: Set catch_workers_output to "yes" in www.conf
  ini_file:
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    section: www
    option: catch_workers_output
    value: yes
