---
- name: Install php {{ php_version }} fpm
  apt:
    pkg: php{{ php_version }}-fpm
    state: present
    install_recommends: no

- name: Creating /run/php directory
  file: 
    path: /run/php
    state: directory
    owner: www-data
    mode: u=rwx,g=rx,o=rx

- name: "Creating /var/log/php directory owner by www-data"
  file: 
    path: /var/log/php
    state: directory
    owner: www-data
    mode: u=rwx,g=rx,o=rx

- name: Register php_fpm_ini_path ("/etc/php/{{ php_version }}/fpm/php.ini")
  set_fact: 
    php_fpm_ini_path: "/etc/php/{{ php_version }}/cli/php.ini"

- name: Adding "/etc/php/{{ php_version }}/fpm/php.ini" to "php_ini_path_list" array
  set_fact: 
    php_ini_path_list: "{{ php_ini_path_list + [ php_fpm_ini_path ] }}"
  when: "php_fpm_ini_path not in php_ini_path_list"

- name: Set max_execution_time to 900 for fpm php.ini
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    section: PHP
    option: max_execution_time
    value: 900

- name: Change owner to www-data for /etc/php
  file:
    dest: /etc/php
    owner: www-data
    recurse: yes

- name: Change owner to www-data for /var/log/php
  file:
    dest: /var/log/php
    owner: www-data
    recurse: yes

- name: Set error_log to "/var/log/php/error.log" in php-fpm.conf
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/php-fpm.conf
    section: global
    option: error_log
    value: /var/log/php/error.log

- name: Set log_level to "notice" in php-fpm.conf
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/php-fpm.conf
    section: global
    option: log_level 
    value: notice
    
- name: Set daemonize to yes in php-fpm.conf
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/php-fpm.conf
    section: global
    option: daemonize
    value: "yes"
    
- name: Setting user to www-data
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    section: www
    option: user 
    value: www-data

- name: Setting group to www-data
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    section: www
    option: group 
    value: www-data

- name: Set listen to 90{{ php_version|default('70')|regex_replace('[^0-9]', '') }} in www.conf
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    section: www
    option: listen 
    value: 90{{ php_version|default('70')|regex_replace('[^0-9]', '') }}

- name: Set request_terminate_timeout to "900s" in www.conf
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    section: www
    option: request_terminate_timeout 
    value: 900s

- name: Set request_slowlog_timeout to "180s" in www.conf
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    section: www
    option: request_slowlog_timeout 
    value: 180s

- name: Set slowlog to "/var/log/php/slow.log" in www.conf
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    section: www
    option: slowlog
    value: /var/log/php/slow.log

- name: Set catch_workers_output to "yes" in www.conf
  ini_file:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    section: www
    option: catch_workers_output
    value: yes
