---
# Someting looks like this: http://moon.srv.today:8086
influxdb_url: "{{ ansible_env.influxdb_url }}"
influxdb_user: "{{ ansible_env.influxdb_user }}"
influxdb_password: "{{ ansible_env.influxdb_password }}"
