---
- hosts: all
  vars: 
    - php_ini_path_list: "{{ ansible_local.php.version|default([]) }}"
    - php_version: "{{ ansible_local.php.version|default(7.0) }}"
  tasks:
    - name: Dump all vars
      action: template src=dump_vars.j2 dest=/tmp/ansible_vars.dump
