---
- hosts: all
  vars: 
    - php_ini_path_list: []
    - php_version: 5.6
  roles:
    - roles/php-base
    - roles/php-fpm
    - roles/php-config
  post_tasks:
    - name: Restart php{{ php_version }}-fpm
      service:
        name: php{{ php_version }}-fpm
        state: restarted
