---
- hosts: all
  vars: 
    - php_ini_path_list: "{{ ansible_local.php.version|default([]) }}"
    - php_version: "{{ ansible_local.php.version|default(5.6) }}"
  roles:
    - roles/tools
    - roles/nginx
    - roles/traefik
    - roles/php-base
    - roles/php-fpm
    - roles/php-config
    - roles/composer
    - roles/nodejs
    - roles/swap
  post_tasks:
    - name: Restart php{{ php_version }}-fpm
      service:
        name: php{{ php_version }}-fpm
        state: restarted
