---
- hosts: all
  vars: 
    - php_ini_path_list: []
    - php_version: 7.0
  roles:
    - roles/tools
    - roles/nginx
    - roles/traefik
    - roles/php-base
    - roles/php-fpm
    - roles/php-config
    - roles/composer
    - roles/nodejs
    - roles/percona-server
