---
- hosts: all
  vars: 
    - php_ini_path_list: "{{ ansible_local.php.version|default([]) }}"
    - php_version: "{{ ansible_local.php.version|default(7.0) }}"
  roles:
    - roles/tools
    - roles/traefik
