---
- name: "Creating /etc/nginx/sites-available/magento1_vhosts.conf"
  template: 
    src: sites-available/magento1_vhosts.conf.j2
    dest: /etc/nginx/sites-available/magento1_vhosts.conf
    owner: root
    group: root


- name: "Link /etc/nginx/sites-enabled/magento1_vhosts.conf"
  file: 
    src: /etc/nginx/sites-available/magento1_vhosts.conf
    dest: /etc/nginx/sites-enabled/magento1_vhosts.conf
    owner: root
    group: root
    state: link

- name: "Adding traefik config"
  blockinfile:
    dest: /etc/traefik/traefik.toml
    marker: "# {mark} VHOSTS"
    block: |
      [frontends.vhosts]
      backend = "vhosts"
      passHostHeader = true
      [frontends.vhosts.routes.default]
      priority = 10
      rule = "PathPrefix:/"
      [backends.vhosts.LoadBalancer]
      method = "wrr"
      [backends.vhosts.servers.localhost]
      url = "http://127.0.0.1:1083"
      weight = 1 

- name: Restart nginx
  service:
    name: nginx
    state: restarted
