---
- name: Install percona repository
  shell: |
    wget https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb
    dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb
  args:
    chdir: /tmp

- name: Update apt cache
  apt: 
    update_cache: yes

- name: Install percona-server-server-5.7
  apt:
    pkg: percona-server-server-5.7
    state: present

- name: Stopping mysql
  service:
    name: mysql
    state: stopped

- name: Setting max_allowed_packet to 512M
  ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: max_allowed_packet
    value: 512M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: max_allowed_packet
    value: 512M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: thread_cache_size
    value: 8

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: wait_timeout
    value: 900

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: sort_buffer_size
    value: 16M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: read_rnd_buffer_size
    value: 16M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: read_buffer_size
    value: 16M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: join_buffer_size
    value: 16M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: key_buffer_size
    value: 512M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: tmp_table_size
    value: 256M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: max_heap_table_size
    value: 256M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: query_cache_size
    value: 64M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: innodb_file_per_table
    value: 1

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: innodb_thread_concurrency
    value: 8

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: innodb_lock_wait_timeout
    value: 300

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: innodb_flush_method
    value: O_DIRECT

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: innodb_log_files_in_group
    value: 2

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: innodb_log_file_size
    value: 256M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: innodb_log_buffer_size
    value: 16M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: innodb_flush_log_at_trx_commit
    value: 2

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: innodb_buffer_pool_size
    value: 1024M

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: lower_case_table_names
    value: 2

- ini_file:
    dest: /etc/mysql/conf.d/mysql.cnf
    section: mysqld
    option: expire_logs_days
    value: 30

- name: Remove log files
  shell: rm -rf /var/lib/mysql/ib*

- name: Setting plugin=mysql_native_password
  shell: "mysqld_safe --skip-grant-tables > /dev/null 2>&1 & sleep 10 && mysql -uroot -e 'update user set plugin=\"mysql_native_password\";' mysql && pgrep mysql | xargs kill -15 && sleep 10"
  args:
    chdir: /tmp

- name: Starting mysql
  service:
    name: mysql
    state: started


