---
redis_version: 3.1.2
php70_modules:
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-dev
  - php7.0-gd
  - php7.0-intl
  - php7.0-mcrypt
  - php7.0-mysql
  - php7.0-pgsql
  - php7.0-xmlrpc
  - php7.0-xsl
  - php7.0-bcmath
  - php7.0-ldap
  - php7.0-soap
  - php7.0-mbstring
  - php7.0-zip 
  - php7.0-bz2
  - php7.0-tidy
