---
- name: Installing php70-dev module
  apt:
    name: "php70-dev"
    state: present

- name: Downloading phpredis-{{ redis_version }}.tar.gz
  get_url:
    url: https://github.com/phpredis/phpredis/archive/{{ redis_version }}.tar.gz
    dest: /tmp/phpredis-{{ redis_version }}.tar.gz

- name: Building php7.0-redis from source
  shell: > 
     tar -zxvf /tmp/phpredis-{{ redis_version }}.tar.gz && \
     cd phpredis-{{ redis_version }} && \
     phpize && \
     ./configure && \
     make > /dev/null && \
     make install > /dev/null && \
     echo "extension=redis.so" > /etc/php/7.0/mods-available/redis.ini
  args:
    chdir: /tmp
    creates: /usr/lib/php/20151012/redis.so

- name: Find php configs
  shell: find /etc/php/7.0 -name conf.d
  register: php_configs

- name: Create link ({{ item }}/20-redis.ini)
  file:
    src: /etc/php/7.0/mods-available/redis.ini
    dest: {{ item }}/20-redis.ini
    state: link
  with_items: "{{ php_configs.stdout }}"
