---
- name: "Creating /etc/nginx/sites-available/magento1.conf"
  template: 
    src: sites-available/magento1.conf.j2 
    dest: /etc/nginx/sites-available/magento1.conf
    owner: root
    group: root

- name: "Link /etc/nginx/sites-enabled/magento1.conf"
  file: 
    src: /etc/nginx/sites-available/magento1.conf
    dest: /etc/nginx/sites-enabled/magento1.conf
    owner: root
    group: root
    state: link

- name: "Adding traefik config"
  blockinfile:
    dest: /etc/traefik/traefik.toml
    marker: "# {mark} MAGENTO1"
    block: |
      [frontends.magento1]
      backend = "magento1"
      passHostHeader = true
      [frontends.magento1.routes.default]
      priority = 10
      rule = "PathPrefix:/"
      [backends.magento1.LoadBalancer]
      method = "wrr"
      [backends.magento1.servers.localhost]
      url = "http://127.0.0.1:1081"
      weight = 1 

- name: Restart nginx
  service:
    name: nginx
    state: restarted
