---
- name: 'Printing php_version'
  debug: var=php_version

- name: "Creating /etc/nginx/sites-available/magento2.conf"
  template: 
    src: sites-available/magento2.conf.j2
    dest: /etc/nginx/sites-available/magento2.conf
    owner: root
    group: root

- name: "Link /etc/nginx/sites-enabled/magento2.conf"
  file: 
    src: /etc/nginx/sites-available/magento2.conf
    dest: /etc/nginx/sites-enabled/magento2.conf
    owner: root
    group: root
    state: link

- name: "Adding traefik config"
  template:
    src: magento2.toml.j2
    dest: /etc/traefik/conf.d/magento2.toml
    owner: root
    group: root

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart traefik
  service:
    name: traefik
    state: restarted
