--- 
- name: "Get latest available Traefik release"
  shell: "echo $(curl -L --silent https://api.github.com/repos/containous/traefik/releases | jq -r '.[].tag_name' | grep 'v1' | head -1)"
  register: traefik_version_output
  
- name: Set fact "traefik_version" to "{{ traefik_version_output.stdout }}" 
  set_fact: 
    traefik_version: "{{ traefik_version_output.stdout }}"

- name: "Downloading Traefik ({{ traefik_version }})"
  get_url:
    url: https://github.com/containous/traefik/releases/download/{{ traefik_version }}/traefik_linux-amd64
    dest: /usr/local/bin/traefik
    mode: 0755
    owner: root
    group: root

- file:
    path: /etc/traefik
    state: directory
    mode: 0755

- file:
    path: /etc/traefik/conf.d
    state: directory
    mode: 0755

- name: "Creating /etc/traefik/traefik.toml"
  template:
    src: traefik.toml.j2
    dest: /etc/traefik/traefik.toml
    owner: root
    group: root

- name: "Creating /lib/systemd/system/traefik.service"
  template:
    src: traefik.service.j2
    dest: /lib/systemd/system/traefik.service
    owner: root
    group: root

- name: "Enable traefik service"
  systemd:
    name: traefik
    state: started
    enabled: yes
