---
- name: "Downloading webmin"
  get_url:
    url: http://prdownloads.sourceforge.net/webadmin/webmin_1.840_all.deb
    dest: /tmp/webmin.deb
    mode: 0755
    owner: root
    group: root

- name: "Install webmin"
  apt: deb="/tmp/webmin.deb"

- name: "Adding traefik config"
  blockinfile:
    dest: /etc/traefik/traefik.toml
    marker: "# {mark} WEBMIN"
    block: |
      [frontends.webmin]
      backend = "webmin"
      passHostHeader = true
      [frontends.webmin.routes.default]
      priority = 10
      rule = "PathPrefixStrip:/webmin"
      [backends.webmin.LoadBalancer]
      method = "wrr"
      [backends.webmin.servers.localhost]
      url = "http://127.0.0.1:10000/"
      weight = 1

- name: "Adding webprefix=/webmin to /etc/webmin/config"
  lineinfile: 
    dest: "/etc/webmin/config"
    line: "webprefix=/webmin"
    state: present

- name: "Adding webprefix=/webmin to /etc/webmin/miniserv.conf"
  lineinfile: 
    dest: "/etc/webmin/miniserv.conf"
    line: "webprefix=/webmin"
    state: present

- name: "Adding webprefixnoredir=1 to /etc/webmin/config"
  lineinfile: 
    dest: "/etc/webmin/config"
    line: "webprefixnoredir=1"
    state: present

- name: "Adding relative_redir=0 to /etc/webmin/config"
  lineinfile: 
    dest: "/etc/webmin/config"
    line: "relative_redir=0"
    state: present
    
- name: "Adding referers={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} to /etc/webmin/config"
  lineinfile: 
    dest: "/etc/webmin/config"
    line: "referers={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    state: present

- name: "Adding referers_none=1 to /etc/webmin/config"
  lineinfile: 
    dest: "/etc/webmin/config"
    line: "referers_none=1"
    state: present

- name: "Adding cookiepath=/webmin to /etc/webmin/miniserv.conf"
  lineinfile: 
    dest: "/etc/webmin/miniserv.conf"
    line: "cookiepath=/webmin"
    state: present

- name: "Adding ssl=0 to /etc/webmin/miniserv.conf"
  lineinfile: 
    dest: "/etc/webmin/miniserv.conf"
    line: "ssl=0"

- name: "Adding ssl_redirect=0 to /etc/webmin/miniserv.conf"
  lineinfile: 
    dest: "/etc/webmin/miniserv.conf"
    line: "ssl_redirect=0"

- name: "Patching /usr/share/webmin/miniserv.pl"
  replace:
    dest: /usr/share/webmin/miniserv.pl
    regexp: \$prot\:\/\/\$hostport\$redir
    replace: $prot://$host$redir

- name: "Patching /usr/share/webmin/miniserv.pl"
  replace:
    dest: /usr/share/webmin/miniserv.pl
    regexp: \$prot\:\/\/\$hostport\$in\{'page'\}
    replace: $prot://$host$config{webprefix}$in{'page'}

- name: "Patching /usr/share/webmin/miniserv.pl"
  replace:
    dest: /usr/share/webmin/miniserv.pl
    regexp: \$prot\:\/\/\$hostport\$page\/
    replace: $prot://$host$page/

- name: Restart traefik
  service:
    name: traefik
    state: restarted

- name: Restart webmin
  service:
    name: webmin
    state: restarted
